version: "3"

services: 
  web: 
    container_name: apppoderjudicial
    restart: always
    build: .
    ports:
      - "8080:3000"
    links: 
      - mongo
    volumes: 
      - .:/usr/src/app    
  mongo: 
    container_name: mymongodatabase    
    image: mongo
    ports: 
      - "27018:27017"
    #environment:
      #- MONGO_INITDB_ROOT_USERNAME=admin
      #- MONGO_INITDB_ROOT_PASSWORD=password  
    logging: 
      driver: none
  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      #- ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      #- ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo 
    restart: unless-stopped
           